### ISSUE TITLE
from_gmsh fails

### ISSUE THREAD

**Issue by sshiraiwa** [SCOREC/core#278] opened 2019-11-21 17:16 UTC
Hi I am getting this error when trying to convert a gmsh file using from_gmsh. I do not have .geo file since it is generated using PythonAPI. Could it be an issue?

$ from_gmsh** .null test_torus.msh test_torus.smb
APF FAILED: apf::Verify: triangle with 2 adjacent regions
centroid: (1.2366, -9.62193e-17, 0.0633975)
based on the following:
 - triangle is classified on a model face
   which is adjacent to 0 model regions
   and is a manifold boundary face
   making the triangle "exposed" at the geometric boundary
we would expect the adjacent region count to be exactly 1

[mfews02:09551] *** Process received signal ***
[mfews02:09551] Signal: Aborted (6)
[mfews02:09551] Signal code:  (-6)
[mfews02:09551] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f02df278f20]
[mfews02:09551] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f02df278e97]
[mfews02:09551] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f02df27a801]
[mfews02:09551] [ 3] /home/shiraiwa/twopi_roots/20190713_py3/lib/libapf.so(+0x45f2f)[0x7f02e078ef2f]
[mfews02:09551] [ 4] /home/shiraiwa/twopi_roots/20190713_py3/lib/libapf.so(+0x8f67a)[0x7f02e07d867a]
[mfews02:09551] [ 5] /home/shiraiwa/twopi_roots/20190713_py3/lib/libapf.so(_ZN3apf6verifyEPNS_4MeshEb+0x7b6)[0x7f02e07d9f66]
[mfews02:09551] [ 6] from_gmsh(main+0x65)[0x55fff0fb2aa5]
[mfews02:09551] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f02df25bb97]
[mfews02:09551] [ 8] from_gmsh(_start+0x2a)[0x55fff0fb2b7a]
[mfews02:09551] *** End of error message ***
Aborted (core dumped)

[test_torus.msh.txt](https://github.com/SCOREC/core/files/3875889/test_torus.msh.txt)

**Comment by mortezah** [comment] 2019-11-21 19:38
@sshiraiwa I just pushed a fix to develop branch 
https://github.com/SCOREC/core/commit/30d5d9fbf064d3a807bdf1fb5a362b73c863bafc

Let me know if there are any other problems.

**Comment by mortezah** [comment] 2019-12-06 18:00
@sshiraiwa were you able to test this out?

Let me know if the problem is fixed so I can close this issue.

**Comment by cwsmith** [comment] 2020-07-17 13:30
I assume this is fixed.  Please reopen if needed.

**Closed by cwsmith** 2020-07-17 13:30 UTC
