### ISSUE TITLE
Segfault in apf::writeVtkFiles

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#20] opened 2015-12-01 04:22 UTC
I was running some old code on travis and I am now getting segfaults when I call apf::writeVtkFiles.

I compiled PUMI at commit d4cecce8bfb4ed25130295b9d55c1559dd1d55d1

This is the error I get
```
$ mpirun ./bin/bug.out 
mesh verified in 0.000027 seconds
end of my code

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 32535 RUNNING AT localhost.localdomain
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

This is my version of mpirun
```
$ mpirun --version
HYDRA build details:
    Version:                                 3.1
    Release Date:                            Thu Feb 20 11:41:13 CST 2014
    CC:                              gcc  -m64 -O2 -fPIC -Wl,-z,noexecstack 
    CXX:                             g++  -m64 -O2 -fPIC -Wl,-z,noexecstack 
    F77:                             gfortran -m64 -O2 -fPIC -Wl,-z,noexecstack 
    F90:                             gfortran -m64 -O2 -fPIC -Wl,-z,noexecstack 
    Configure options:                       '--disable-option-checking' '--prefix=/usr' '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-sharedlibs=gcc' '--enable-shared' '--enable-lib-depend' '--disable-rpath' '--enable-fc' '--with-device=ch3:nemesis' '--with-pm=hydra:gforker' '--includedir=/usr/include/mpich-x86_64' '--bindir=/usr/lib64/mpich/bin' '--libdir=/usr/lib64/mpich/lib' '--datadir=/usr/share/mpich' '--mandir=/usr/share/man/mpich' '--docdir=/usr/share/mpich/doc' '--htmldir=/usr/share/mpich/doc' '--with-hwloc-prefix=system' 'FC=gfortran' 'F77=gfortran' 'CFLAGS=-m64 -O2 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2' 'CXXFLAGS=-m64 -O2 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'FCFLAGS=-m64 -O2 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'FFLAGS=-m64 -O2 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2' 'LDFLAGS=-Wl,-z,noexecstack ' 'MPICHLIB_CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'MPICHLIB_CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'MPICHLIB_FCFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'MPICHLIB_FFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'LIBS=-lrt -lpthread ' 'CPPFLAGS= -I/builddir/build/BUILD/mpich-3.1/src/mpl/include -I/builddir/build/BUILD/mpich-3.1/src/mpl/include -I/builddir/build/BUILD/mpich-3.1/src/openpa/src -I/builddir/build/BUILD/mpich-3.1/src/openpa/src -I/builddir/build/BUILD/mpich-3.1/src/mpi/romio/include'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select

```

Here is a minimal working example, using vanilla apf mesh functions to build a single quad, then attempt to serialize it to disk using apf::writeVtkFiles

```C++
#include <stdint.h>
#include <stdio.h>
#include <iostream>
#include <iomanip>
#include <cmath>
#include <cassert>

#include <apf.h>
#include <apfMesh2.h>
#include <apfMesh.h>
#include <gmi_mesh.h>
#include <gmi_null.h>
#include <apfShape.h>
#include <gmi_mesh.h>
#include <gmi_null.h>
#include <apfMDS.h>
#include <PCU.h>
#include <apfNumbering.h>

#define SECRET_BUILDER_NUMBERING "SecretBuilderNumbering"

int main(int argc, char *argv[])
{
	MPI_Init(&argc,&argv);
  	PCU_Comm_Init();

	apf::Mesh2* mesh = NULL;
	

	gmi_register_null();
	gmi_model* g = gmi_load(".null");
	mesh = apf::makeEmptyMdsMesh(g, 2, false);

	apf::Numbering* numbers = apf::createNumbering(mesh,SECRET_BUILDER_NUMBERING, 
												   mesh->getShape(), 1);
	apf::MeshEntity** vertices = new apf::MeshEntity*[4];
	for(uint32_t counter = 0; counter < 4; counter++) {
		vertices[counter] = mesh->createVert(0);
		apf::number(numbers,vertices[counter],0,0,counter);
	}


	/*this element is flipped upside down around x axis*/
	apf::Vector3 tmp_vec(1.35,2.36,0.0);
	mesh->setPoint(vertices[0], 0, tmp_vec);
	tmp_vec.x() = 2.57; tmp_vec.y() = 2.70;
	mesh->setPoint(vertices[1], 0, tmp_vec);
	tmp_vec.x() = 2.51; tmp_vec.y() = 1.75;
	mesh->setPoint(vertices[2], 0, tmp_vec);
	tmp_vec.x() = 1.64; tmp_vec.y() = 1.28;
	mesh->setPoint(vertices[3], 0, tmp_vec);

	apf::buildElement(mesh, NULL, apf::Mesh::QUAD, vertices);

	apf::deriveMdsModel(mesh);
	mesh->acceptChanges();
	mesh->verify();

	apf::changeMeshShape(mesh, apf::getLagrange(2));
	apf::MeshIterator *it;
	apf::MeshEntity* e;
	it = mesh->begin(2);
	e = mesh->iterate(it);

	apf::Downward down;
	uint32_t sz = mesh->getDownward(e, 1, down);
	assert(4 == sz);
	tmp_vec.x() = 2.09; tmp_vec.y() = 2.36;
	mesh->setPoint(down[0], 0, tmp_vec);
	tmp_vec.x() = 2.73; tmp_vec.y() = 2.25;
	mesh->setPoint(down[1], 0, tmp_vec);
	tmp_vec.x() = 2.01; tmp_vec.y() = 1.72;
	mesh->setPoint(down[2], 0, tmp_vec);
	tmp_vec.x() = 1.15; tmp_vec.y() = 1.77;
	mesh->setPoint(down[3], 0, tmp_vec);
	/*set the center node*/
	tmp_vec.x() = 1.90; tmp_vec.y() = 2.05;
	mesh->setPoint(e, 0, tmp_vec);
	delete[] vertices;

	std::cout << "end of my code" << std::endl;

	apf::writeVtkFiles("batman_elm", mesh);

	PCU_Comm_Free();
	MPI_Finalize();

	return 0;
}
```

**Comment by YetAnotherMinion** [comment] 2015-12-01 04:31
Looking into this further I see that the vtk now writes in binary format.

I believe this segfault only happens for certain meshes. I successfully wrote a quadratic triangle element to binary format and loaded it with ParaView using the same build of PUMI with a different mesh my code built from scratch

**Comment by YetAnotherMinion** [comment] 2015-12-01 04:43
Confirm that bug depends on mesh. I works for triangles, here is test code below, not a working example because you will need some files I wrote:

[MeshBuilder.h]( https://github.com/YetAnotherMinion/FEP/blob/master/a4/inc/MeshBuilder.h ) has a bunch of utility functions to build some simple meshes
[MeshBuilder.cc](https://github.com/YetAnotherMinion/FEP/blob/master/a4/src/MeshBuilder.cc) implementation

```C++
#include <stdint.h>
#include <stdio.h>
#include <iostream>
#include <iomanip>
#include <cmath>
#include <cassert>

#include <apf.h>
#include <apfMesh2.h>
#include <apfMesh.h>
#include <gmi_mesh.h>
#include <gmi_null.h>
#include <apfShape.h>
#include <gmi_mesh.h>
#include <gmi_null.h>
#include <apfMDS.h>
#include <PCU.h>
#include <apfNumbering.h>

#include "MeshBuilder.h"

#include <unistd.h>

#define SECRET_BUILDER_NUMBERING "SecretBuilderNumbering"

int main(int argc, char *argv[])
{
	MPI_Init(&argc,&argv);
  	PCU_Comm_Init();

	apf::Mesh2* mesh = NULL;
	MeshBuilder* mesh_builder = new MeshBuilder();
	mesh_builder->build2DRectTriMesh(mesh, 2, 1, 0, 0, 1, 1);

	

	std::cout << "end of my code" << std::endl;
	usleep(1000000);

	apf::writeVtkFiles("tri_test", mesh);

	PCU_Comm_Free();
	MPI_Finalize();

	return 0;
}
```

**Comment by YetAnotherMinion** [comment] 2015-12-01 04:48
I think @paulrevere4 is the most qualified to comment on this. I see he has made a lot of changes to apfVtk.cc since Nov 17.

**Comment by paulrevere4** [comment] 2015-12-01 04:50
Hi, @YetAnotherMinion I will look into this issue. Until it is resolved try using apf::writeASCIIVtkFiles as that will avoid using the changes I made recently.

**Comment by YetAnotherMinion** [comment] 2015-12-01 05:05
Running git bisect identifies
```
ca80bf450d4da92b577d89b81373f0feb2b4f3f0 is the first bad commit
commit ca80bf450d4da92b577d89b81373f0feb2b4f3f0
Author: paulrevere4 <revereiv@gmail.com>
Date:   Tue Nov 17 15:09:19 2015 -0500

    Switched writeVtkFiles and writeOneVtkFile to write with binary encoding
    
    Also made a file to call ascii encoding

:040000 040000 0e0361b4306ea83d82d5dbad3e22a59860ffa985 02ebff0e28611d211ddc5ba341c9d5837217de91 M	apf
:040000 040000 63a3799e7292b87ca19959f1d3ed30c546df07df 8b2d8075e22e47c5c0ba2ceea7234d1c0cce1f59 M	test
```

**Comment by YetAnotherMinion** [comment] 2015-12-01 05:06
Also thanks for the heads up about the writeASCIIVtkFiles , I will switch for now.

**Comment by paulrevere4** [comment] 2015-12-01 18:39
@YetAnotherMinion I ran the first test case that you provided and I had no issues. apf::writeVtkFiles generated the files for paraview without an issue.

Here is the output when I run it 
```
$ mpirun ./bug 
mesh verified in 0.000014 seconds
end of my code
writeVtuFile into buffers: 0.000211 seconds
writeVtuFile buffers to disk: 0.001144 seconds
vtk files batman_elm written in 0.002612 seconds
```

Here is my version of mpirun 

```
$ mpirun --version
HYDRA build details:
    Version:                                 3.1.2
    Release Date:                            Mon Jul 21 16:00:21 CDT 2014
    CC:                              gcc    
    CXX:                             g++    
    F77:                             gfortran   
    F90:                             gfortran   
    Configure options:                       '--disable-option-checking' '--prefix=/usr/local/mpich3/3.1.2-thread-multiple' '--enable-threads=multiple' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= -O2' 'LDFLAGS= ' 'LIBS=-lrt -lpthread ' 'CPPFLAGS= -I/usr/src/mpich-3.1.2/src/mpl/include -I/usr/src/mpich-3.1.2/src/mpl/include -I/usr/src/mpich-3.1.2/src/openpa/src -I/usr/src/mpich-3.1.2/src/openpa/src -D_REENTRANT -I/usr/src/mpich-3.1.2/src/mpi/romio/include'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select
```

I will still look to see why the issue is occurring. Like I said, feel free to use the apf::writeASCIIVtkFiles function as that will write the vtk files you're looking for and skip the changes I have recently made for compression and binary formatting.

**Comment by ibaned** [comment] 2015-12-03 00:01
Its been a while since last activity, so I'm closing this.
Reopen if you have a program that actually reproduces
the failure for us.

**Comment by YetAnotherMinion** [comment] 2015-12-03 02:18
It has been two days, also there is a complete working program to trigger the bug in the very first comment. Paul already said he was looking into it. Being an undergraduate I imagine that his schedule does not allow for immediate debugging. 



On Dec 2, 2015, at 7:01 PM, Dan Ibanez <notifications@github.com> wrote:

Its been a while since last activity, so I'm closing this.
Reopen if you have a program that actually reproduces
the failure for us.

**Comment by ibaned** [comment] 2015-12-03 02:20
Paul and I ran that program together yesterday. It worked fine and Valgrind pointed out no issues. So unless you provide something more, we can't reproduce the segfault and you'll have to trace it yourself.

**Comment by YetAnotherMinion** [comment] 2015-12-03 02:39
That is useful information to know. Could you show `mpirun --version` that you used?



On Dec 2, 2015, at 9:20 PM, Dan Ibanez <notifications@github.com> wrote:

Paul and I ran that program together yesterday. It worked fine and Valgrind pointed out no issues. So unless you provide something more, we can't reproduce the segfault and you'll have to trace it yourself.

**Closed** 2015-12-08 14:15 UTC
Labels: bug

**Comment by ibaned** [comment] 2015-12-12 02:29
For what its worth, we were eventually able to reproduce this and fix it.
It was a loop-bound unsigned wraparound that would only be triggered
for meshes with two or fewer elements.

Why this only segfaults with a particular build configuration, including
shared libraries, is beyond me.

https://github.com/SCOREC/core/commit/67b1aa64076dc7303442bf3155b3889ae3922585#diff-3ce282682957447754aa33baa75bc240R140

**Comment by YetAnotherMinion** [comment] 2015-12-12 02:54
I am glad that this puzzle was solved. I was actually unable to reproduce the very next day on my machine, which made me wonder if I was going crazy...
