### ISSUE TITLE
creating a mesh from fluent topology

### ISSUE THREAD

**Issue by ztdepztdep** [SCOREC/core#265] opened 2019-10-21 02:49 UTC
Dear sir:  
    I want a serial "smb" mesh with the follow code:
 ``` C
for (int i = 0; i < FVM.NCELL; ++i) {
  for(int j=0;j<4;j++) {
    for(int jj=0;jj<3;jj++) {  
      points[j][jj]=FVM.FluentNodes[FVM.FluentCellConnection[i][j]][jj];
    }
    vertices[j] = pumi_mesh_createVtx(mesh, NULL, points[j]); 
   }
   pumi_mesh_createElem(mesh, NULL, PUMI_TET, vertices);   
}

pumi_mesh_createAdjacency(mesh, 3,2);
cout<<pumi_mesh_hasAdjacency (mesh, 3,2)<<endl;

pumi_mesh_freeze(mesh);
pumi_mesh_verify(mesh);
pumi_mesh_write(mesh, "./output2/fluent.smb", "mds");
pumi_mesh_delete(mesh);`

```
  and then load it with 
```
pGeom g2 = pumi_geom_load(NULL, "null");
 pMesh mesh2 = pumi_mesh_load(g2,"./output2/fluent.smb", 1);
mesh2->verify();
 apf::writeVtkFiles("./output/d1", mesh2);
```

```
  But the code gives me the error:
mesh ./output2/fluent.smb loaded in 0.478128 seconds
number of tet 46825 hex 0 prism 0 pyramid 0
mesh entity counts: v 187300 e 280950 f 187300 r 46825
PARMETIS ERROR adjncy is NULL.
planned Zoltan split factor 12 to target imbalance 1.050000 in 0.112204 seconds
mesh expanded from 1 to 12 parts in 0.271982 seconds
APF warning: 11 empty parts
mesh migrated from 1 to 12 in 1.411997 seconds
```

  Coudl you please give me some suggestion how to resolve this.

edit: code formatting

**Comment by cwsmith** [comment] 2019-10-21 12:14
The problem is that the same vertex is created multiple times for different elements.  You'll need a loop over unique vertices that calls `vertices[i] = pumi_mesh_createVtx(...)`.  Then call `pumi_mesh_createElem()` for each element using the correct set of indices from the `vertices` array.

**Comment by ztdepztdep** [comment] 2019-10-22 06:27
Thanks, it works now. But the ouput mesh still has only 1 part. I run it with 6 processes. 
![11](https://user-images.githubusercontent.com/8356693/67262574-e940e100-f4d7-11e9-8ae3-48296df3b6b4.png)
```

for (int i = 0; i < FVM.NV; i++)
{
  for(int jj=0;jj<3;jj++)
     point[jj]=FVM.FluentNodes[i][jj];
     vertices[i] = pumi_mesh_createVtx(mesh, NULL, point); 
}

for (int i = 0; i < FVM.NCELL; ++i)
{
  for(int j=0;j<4;j++)
    vertice[j]=vertices[FVM.FluentCellConnection[i][j]];pumi_mesh_createElem(mesh, NULL, PUMI_TET, vertice);   
}

//pumi_mesh_createAdjacency(mesh, 3,2);
//cout<<pumi_mesh_hasAdjacency (mesh, 3,2)<<endl;
 
 pumi_mesh_freeze(mesh);
 pumi_mesh_verify(mesh);
 pumi_mesh_write(mesh,"./output/d11", "vtk");
```

**Comment by cwsmith** [comment] 2019-10-22 12:00
Try writing the mesh as an '.smb' (the 'mds' format) and then running `zsplit` on it.

**Comment by ztdepztdep** [comment] 2019-10-22 22:00
> Try writing the mesh as an '.smb' (the 'mds' format) and then running `zsplit` on it.

Thanks. Does pumi has api for "zsplit"

**Comment by jacobmerson** [comment] 2019-10-23 04:06
You can see the code for zsplit [here](https://github.com/SCOREC/core/blob/d245e9224d4ce742356ae7b21c2582d32c3f41ec/test/zsplit.cc). 

Relevant lines where the zZoltan graph partitioner is used:
https://github.com/SCOREC/core/blob/d245e9224d4ce742356ae7b21c2582d32c3f41ec/test/zsplit.cc#L31-L41

**Comment by ztdepztdep** [comment] 2019-10-23 06:26
> Try writing the mesh as an '.smb' (the 'mds' format) and then running `zsplit` on it.

I have output the smb mesh file. but zsplit need the geometry file also. How to ouput it Since i have only the mesh file.

**Comment by cwsmith** [comment] 2019-10-23 14:23
You can pass `'.null'` as the argument for the geometric model if you don't have a parasolid, acis or discrete model.

**Comment by cwsmith** [comment] 2019-10-31 12:13
@ztdepztdep Were you able to partition your mesh?

**Comment by ztdepztdep** [comment] 2019-11-04 04:56
> @ztdepztdep Were you able to partition your mesh?
Thanks. I work with gmsh now. I will work on fluent mesh again later.

**Comment by cwsmith** [comment] 2019-11-04 12:59
OK.  I'm going to close this issue. Please reopen if needed.

**Closed by cwsmith** 2019-11-04 12:59 UTC
Labels: mesh file formats, mesh generation, pumi api
