### ISSUE TITLE
getUp for sim mesh

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#71] opened 2017-02-02 15:35 UTC
https://github.com/SCOREC/core/blob/8b6e65a14ca23dfe6087c289e5c13d039bcb5c52/apf_sim/apfSIM.cc#L409

Why do we have this loop? I mean, directly returning the ith region seems fine to me.

**Comment by zhang-alvin** [comment] 2017-02-02 15:59
MeshSIM::getUp is actually causing me issues when trying to use a Simmetrix mesh with apf-sim in Proteus. An upward adjacency of an interior mesh face shows that it is adjacent to two regions with the same region ID. A call to apf::getAdjacent(), however, yields different results.

**Comment by bgranzow** [comment] 2017-02-02 16:08
@zhang-alvin would it make sense to try to use the Simmetrix APIs directly to query the adjacencies you want to get some sense of what getUp and getAdjacent should actually return?

**Comment by zhang-alvin** [comment] 2017-02-02 16:21
@bgranzow I think that is sensible, but I've already made an independent program to test the results of getUp and getAdjacent for both a mesh created from apf::createMesh() and a mesh created from apf::createMdsMesh(). For the createMdsMesh, I get consistent results between getUp and getAdjacent. A quick look via the Simmetrix GUI shows that at the very least, the resultant regions are in fact adjacent to each other. For the createMesh() mesh, only the getAdjacent() call gives me adjacencies consistent  with the MdsMesh.

**Comment by bgranzow** [comment] 2017-02-02 16:36
So just to be clear, you are saying that call apf::MeshSim::getUp
https://github.com/SCOREC/core/blob/master/apf_sim/apfSIM.h#L48
on a mesh face interior to the geometry. This function fills in the apf::Up struct
https://github.com/SCOREC/core/blob/master/apf/apfMesh.h#L63
so that up.n = 2,
and you believe the two entities stored in up.e have the same ID? What do you mean by region ID?

Or am I completely off-base and you are talking about something like a non-manifold model ?

**Comment by zhang-alvin** [comment] 2017-02-02 16:48
@bgranzow That's right. If I do a getNumber() on the two entities stored I get the same value. By region, I just mean a mesh element in 3D. I can point you my test program for closer scrutiny?

**Comment by bgranzow** [comment] 2017-02-02 17:40
@zhang-alvin , sure sounds good.

**Comment by zhang-alvin** [comment] 2017-02-02 17:54
@bgranzow The following path contains an executable a.out that loads a mesh from model_and_mesh. The source code is in sample_load.cc and the compile and run scripts are labeled accordingly: /users/zhanga/Projects/TESTS/apf_sim_test_1.30.2017

**Comment by ibaned** [comment] 2017-02-02 17:54
Although I can't speak to @zhang-alvin's bug, the loop pointed out by @yangf4 is supposed to handle faces on the boundary of the mesh. I think I was seeing cases in which:

```
F_region(face, 0) == NULL
F_region(face, 1) != NULL
```

Seems like this needs to be re-investigated though.

**Comment by bgranzow** [comment] 2017-03-23 13:48
@zhang-alvin & @yangf4, I think @ibaned may have fixed this issue in #92. Can you please retry your test code and see if it behaves as expected?

**Comment by bgranzow** [comment] 2017-03-28 02:27
I'm closing this as I am pretty sure it's fixed. Please re-open if you still run into trouble.

**Closed by bgranzow** 2017-03-28 02:27 UTC

**Comment by zhang-alvin** [comment] 2017-03-28 02:34
Yes, I think the problem is resolved, sorry for the lack of follow-up.
